name: run unit tests
on: pull_request
jobs:
  run-unit-tests:
    name: run unit tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes","devtools", "rmarkdown","tidyverse","DT","here"))
          remotes::install_deps(dependencies = NA)
        shell: Rscript {0}
      - name: Install zoltr and scoringutils
        run: |
          devtools::install_github("reichlab/zoltr")
          devtools::install_github("epiforecasts/scoringutils")
          devtools::install()
        shell: Rscript {0}
      - name: Check 
        run: |
          devtools::check(args = c("--no-tests", "--no-vignettes"), force_suggests = FALSE, error_on = c("error"))
        shell: Rscript {0}
      - name: Run unit tests
        run: |
          devtools::test_active_file("tests/testthat/test-date_management.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-score_forecasts.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-load_forecast_files_repo.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-get_model_designations.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-load_as_of.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-load_truth.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-calc_cramers_dist_equal_space.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-calc_cramers_dist_unequal_space.R", stop_on_failure = TRUE)
          devtools::test_active_file("tests/testthat/test-calc_cramers_dist_one_model_pair.R", stop_on_failure = TRUE)
        shell: Rscript {0}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1
      - name: Checkout covidData when get_truth.R has changed 
        if: contains(steps.changed-files.outputs.modified_files, 'R/get_truth.R')
        uses: actions/checkout@v2
        with:
          repository: reichlab/covidData
          path: covidData
      - name: Install covidData when get_truth.R has changed 
        if: contains(steps.changed-files.outputs.modified_files, 'R/get_truth.R')
        run: make recent_data
        working-directory: ./covidData/code/data-processing
      - name: Run unit test for get_truth.R
        if: contains(steps.changed-files.outputs.modified_files, 'R/get_truth.R')
        run: |
          devtools::test_active_file("tests/testthat/test-get_truth.R", stop_on_failure = TRUE)
        shell: Rscript {0}
      - name: Render vignettes
        run: |
          rmarkdown::render("vignettes/covidHubUtils-overview.Rmd")
        shell: Rscript {0}
    
          
        


